### ISSUE TITLE
No dcoumentation

### ISSUE THREAD

**Issue by tbergstedt** [appccelerate/Version#16]
We've been using this tool for assembly versioning for some time now. Noticed today that the link to the documentation isn't working anymore. Perhaps best solution would be to enter the whole documentation into the readme?

**Comment by ursenzler** [comment]
It would be yes, but I stopped maintaining this library a long time ago.
But if you have a question, I hope I can answer it here.

**Comment by ursenzler** [comment]
Link to the old docu (source): https://github.com/appccelerate/appccelerate.github.com/blob/master/version.html

**Comment by tbergstedt** [comment]
I don't have any questions at the moment - the tool is simple enough! Also thought it might be worth knowing that it's still used :).
